SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[REBI14_PERMESSI_UTENTE](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[USERNAME_REBI06] [varchar](50) NOT NULL,
	[ID_MENU_REBI08] [int] NOT NULL,
	[FLG_VISIBLE] [decimal](1, 0) NOT NULL,
 CONSTRAINT [PK_REBI14_PERMESSI_UTENTE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO